### ISSUE TITLE
Got unknown argument class: String[]

### ISSUE THREAD

**Issue by callcter** [LewinJun/react-native-lewin-screen-capture#1]
根据 Example 来的

**Comment by zisheng-ai** [comment]
问题解决了吗？

**Comment by LewinJun** [comment]
最近很少看github,  有详细的错误消息吗？     ScreenCaptureUtil.startListener(res=>{
            console.log(res)
            // this.setState({uri:'data:image/png;base64,' + res.base64})
            this.setState({uri: res.uri})
          },['abc','test'])  换成数组试试

**Comment by zisheng-ai** [comment]
这是 logcat 打印的
```
2019-06-11 16:09:44.681 9720-9762/com.veronica E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Got unknown argument class: String[]
        at com.facebook.react.bridge.JavaMethodWrapper.buildArgumentExtractors(JavaMethodWrapper.java:311)
        at com.facebook.react.bridge.JavaMethodWrapper.processArguments(JavaMethodWrapper.java:236)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:346)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:198)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)2019-06-11 16:09:44.681 9720-9762/com.veronica E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Got unknown argument class: String[]
        at com.facebook.react.bridge.JavaMethodWrapper.buildArgumentExtractors(JavaMethodWrapper.java:311)
        at com.facebook.react.bridge.JavaMethodWrapper.processArguments(JavaMethodWrapper.java:236)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:346)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:198)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by zisheng-ai** [comment]
![image](https://user-images.githubusercontent.com/13204332/59254849-8d319a80-8c63-11e9-8a44-5972e63ed8e5.png)

**Comment by zisheng-ai** [comment]
@LewinJun 换成数组也是一样的错误

**Comment by zisheng-ai** [comment]
![image](https://user-images.githubusercontent.com/13204332/59256852-5e1d2800-8c67-11e9-92f7-6cf3bc277520.png)
我看参数顺序不对啊

**Comment by zisheng-ai** [comment]
兄弟，可以修一下这个BUG吗？

**Comment by LewinJun** [comment]
稍等，今天我改好，工作比较忙

**Comment by LewinJun** [comment]
v1.0.7 版本，已解决
